// Code generated by scripts/generate-plugin-imports.ps1; DO NOT EDIT.
// This file is automatically generated to import all compile-time plugins.
// Run 'make discover-plugins' to regenerate.

//go:build !noplugins
// +build !noplugins

package main

import (
	_ "github.com/echterhof/rockstar-web-framework/plugins/auth-plugin"
	_ "github.com/echterhof/rockstar-web-framework/plugins/cache-plugin"
	_ "github.com/echterhof/rockstar-web-framework/plugins/captcha-plugin"
	_ "github.com/echterhof/rockstar-web-framework/plugins/logging-plugin"
	_ "github.com/echterhof/rockstar-web-framework/plugins/storage-plugin"
	_ "github.com/echterhof/rockstar-web-framework/plugins/template"
)
