-- Save workload metrics to the database (PostgreSQL)
-- Parameters: timestamp, tenant_id, user_id, request_id, duration_ms, context_size, 
--             memory_usage, cpu_usage, path, method, status_code, response_size, error_message
-- Note: ID is auto-generated by PostgreSQL's BIGSERIAL

INSERT INTO workload_metrics (
    timestamp, tenant_id, user_id, request_id, duration_ms, context_size, 
    memory_usage, cpu_usage, path, method, status_code, response_size, error_message
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
);
