# Generate plugin import statements for cmd/rockstar/main.go
# This script scans the plugins/ directory and generates import statements

$PluginsDir = "plugins"
$OutputFile = "cmd/rockstar/plugin_imports.go"

# Check if plugins directory exists
if (-not (Test-Path $PluginsDir)) {
    Write-Host "No plugins directory found"
    exit 0
}

# Start generating the file
$content = @"
// Code generated by scripts/generate-plugin-imports.ps1; DO NOT EDIT.
// This file is automatically generated to import all compile-time plugins.
// Run 'make discover-plugins' to regenerate.

//go:build !noplugins
// +build !noplugins

package main

import (
"@

$foundPlugins = $false

# Find all plugin directories and generate imports
Get-ChildItem -Path $PluginsDir -Directory | ForEach-Object {
    $pluginDir = $_.FullName
    $pluginFile = Join-Path $pluginDir "plugin.go"
    
    if (Test-Path $pluginFile) {
        $pluginName = $_.Name
        $content += "`n`t_ `"github.com/echterhof/rockstar-web-framework/plugins/$pluginName`""
        $foundPlugins = $true
    }
}

# Close the import block
$content += "`n)"

if ($foundPlugins) {
    Set-Content -Path $OutputFile -Value $content
    Write-Host "Generated plugin imports in $OutputFile"
} else {
    Write-Host "No plugins found in $PluginsDir"
    # Create empty file with build tag
    $emptyContent = @"
// Code generated by scripts/generate-plugin-imports.ps1; DO NOT EDIT.
// No plugins found.

//go:build !noplugins
// +build !noplugins

package main
"@
    Set-Content -Path $OutputFile -Value $emptyContent
}
