#!/bin/bash
# Generate plugin import statements for cmd/rockstar/main.go
# This script scans the plugins/ directory and generates import statements

set -e

PLUGINS_DIR="plugins"
OUTPUT_FILE="cmd/rockstar/plugin_imports.go"

# Check if plugins directory exists
if [ ! -d "$PLUGINS_DIR" ]; then
    echo "No plugins directory found"
    exit 0
fi

# Start generating the file
cat > "$OUTPUT_FILE" <<EOF
// Code generated by scripts/generate-plugin-imports.sh; DO NOT EDIT.
// This file is automatically generated to import all compile-time plugins.
// Run 'make discover-plugins' to regenerate.

//go:build !noplugins
// +build !noplugins

package main

import (
EOF

# Find all plugin directories and generate imports
found_plugins=false
for plugin_dir in "$PLUGINS_DIR"/*; do
    if [ -d "$plugin_dir" ] && [ -f "$plugin_dir/plugin.go" ]; then
        plugin_name=$(basename "$plugin_dir")
        echo "	_ \"github.com/echterhof/rockstar-web-framework/plugins/$plugin_name\"" >> "$OUTPUT_FILE"
        found_plugins=true
    fi
done

# Close the import block
echo ")" >> "$OUTPUT_FILE"

if [ "$found_plugins" = true ]; then
    echo "Generated plugin imports in $OUTPUT_FILE"
else
    echo "No plugins found in $PLUGINS_DIR"
    # Create empty file with build tag
    cat > "$OUTPUT_FILE" <<EOF
// Code generated by scripts/generate-plugin-imports.sh; DO NOT EDIT.
// No plugins found.

//go:build !noplugins
// +build !noplugins

package main
EOF
fi
