-- Save workload metrics to the database (MySQL)
-- Parameters: timestamp, tenant_id, user_id, request_id, duration_ms, context_size, 
--             memory_usage, cpu_usage, path, method, status_code, response_size, error_message
-- Note: ID is auto-generated by MySQL's AUTO_INCREMENT

INSERT INTO workload_metrics (
    timestamp, tenant_id, user_id, request_id, duration_ms, context_size, 
    memory_usage, cpu_usage, path, method, status_code, response_size, error_message
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
);
